model_params:
  n_estimators: 100
  learning_rate: 0.3
  max_depth: 6

test_patient:
  gender: "Female"
  age: 65.0
  hypertension: 1
  heart_disease: 1
  smoking_history: "current"
  bmi: 35.0
  occupation: "manual_labor"
  family_history: 1
  drinking: "heavy"
  altitude: "low_0-500m"
